name: 2020.2.18 SAST 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@v1.0.3
      with:
        cxAction: Scan
        cxSkipIfFail: true
        cxServer: https://0d5bc6e68afc.ngrok.io
        cxUsername: ${{ secrets.CX_USER }}
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: ${{ secrets.CX_TEAM }}
        cxVersion: "2020.2.18"
        cxLog: log.log
    - name: Upload ReportXML artifact
      uses: actions/upload-artifact@v2.0.1
      with:
        name: report.xml
        path: report.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v2.0.1
      with:
        name: log.log
        path: log.log
