name: 2020.2.18 SAST 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@v1.0.3
      with:
        cxServer: https://0d5bc6e68afc.ngrok.io
        cxUsername: ${{ secrets.CX_EMAIL }}
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: ${{ secrets.CX_TEAM }}
